### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by desmonHak** [jorgeajimenezl/animeflv-api#15]
```py
>>> a = api.get_anime_info("one-punch-man")
>>> a.episodes
[EpisodeInfo(id=12, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/12/th_3.jpg'), EpisodeInfo(id=11, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/11/th_3.jpg'), EpisodeInfo(id=10, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/10/th_3.jpg'), EpisodeInfo(id=9, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/9/th_3.jpg'), EpisodeInfo(id=8, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/8/th_3.jpg'), EpisodeInfo(id=7, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/7/th_3.jpg'), EpisodeInfo(id=6, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/6/th_3.jpg'), EpisodeInfo(id=5, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/5/th_3.jpg'), EpisodeInfo(id=4, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/4/th_3.jpg'), EpisodeInfo(id=3, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/3/th_3.jpg'), EpisodeInfo(id=2, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/2/th_3.jpg'), EpisodeInfo(id=1, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/1/th_3.jpg')]
>>> a.episodes[0]
EpisodeInfo(id=12, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/12/th_3.jpg')
>>> api.get_links("one-punch-man", a.episodes[0])
Traceback (most recent call last):
  File "C:\Users\desmon0xff\Downloads\animeflv-api\animeflv\animeflv.py", line 131, in get_links
    rows = parse_table(table)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\desmon0xff\Downloads\animeflv-api\animeflv\animeflv.py", line 31, in parse_table
    columns = list([x.string for x in table.thead.tr.find_all("th")])
                                      ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'thead'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\desmon0xff\Downloads\animeflv-api\animeflv\animeflv.py", line 154, in get_links
    raise AnimeFLVParseError(exc)
animeflv.exception.AnimeFLVParseError: 'NoneType' object has no attribute 'thead'
```

**Comment by Ninjakito** [comment]
La función `get_links` espera dos parámetros:
1. El **ID del anime** (como string).
2. El **número** o ID del episodio (como entero).

Lo que estás haciendo actualmente es pasar el ID del anime y el objeto completo del episodio, algo así:

`EpisodeInfo(id=12, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/12/th_3.jpg')`

Pero deberías pasar solo el **ID del episodio**, es decir, el **número** que identifica ese capítulo. Por ejemplo, en tu caso:

`api.get_links("one-punch-man", a.episodes[0].id)`

O explícitamente:

`api.get_links("one-punch-man", 12)`

Con esto, la función devolverá los datos correctamente.

Aquí un ejemplo completo para que veas cómo funciona:

```python
>>> a = api.get_anime_info("one-punch-man")
>>> a.episodes
[EpisodeInfo(id=12, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/12/th_3.jpg'), EpisodeInfo(id=11, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/11/th_3.jpg'), EpisodeInfo(id=10, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/10/th_3.jpg'), EpisodeInfo(id=9, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/9/th_3.jpg'), EpisodeInfo(id=8, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/8/th_3.jpg'), EpisodeInfo(id=7, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/7/th_3.jpg'), EpisodeInfo(id=6, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/6/th_3.jpg'), EpisodeInfo(id=5, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/5/th_3.jpg'), EpisodeInfo(id=4, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/4/th_3.jpg'), EpisodeInfo(id=3, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/3/th_3.jpg'), EpisodeInfo(id=2, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/2/th_3.jpg'), EpisodeInfo(id=1, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/1/th_3.jpg')]
>>> a.episodes[0]
EpisodeInfo(id=12, anime='one-punch-man', image_preview='https://cdn.animeflv.net/screenshots/2218/12/th_3.jpg')
>>> api.get_links("one-punch-man", a.episodes[0].id)
[DownloadLinkInfo(server='MEGA', url='https://mega.nz/#!RtNxEIBC!f7KPFyhjVqZPH6IbBbNil7r_1ZI3gyZbgZd74AtHe9Q'), DownloadLinkInfo(server='1Fichier', url='https://1fichier.com/?q5e0johqchkl41hq4x9r'), DownloadLinkInfo(server='Zippyshare', url='http://www59.zippyshare.com/v/K4CbYkL3/file.html'), DownloadLinkInfo(server='Stape', url='https://streamtape.com/v/mvb3Mbrx0mcbW48/')]
```

Prueba con eso y a ver si consigues solucionarlo.

**Comment by desmonHak** [comment]
va a ratos, mira, a veces funciona, y a veces no:
```python
C:\Users\desmon0xff\Desktop>python downloader_animeflv.py
Traceback (most recent call last):
  File "downloader_animeflv.py", line 10, in <module>
    anime_info = api.get_anime_info(anime_id)
  File "C:\Users\desmon0xff\AppData\Local\Programs\Python\Python38\lib\site-packages\animeflv\animeflv.py", line 290, in get_anime_info
    "title": soup.select_one(
AttributeError: 'NoneType' object has no attribute 'string'

C:\Users\desmon0xff\Desktop>python downloader_animeflv.py
Traceback (most recent call last):
  File "downloader_animeflv.py", line 10, in <module>
    anime_info = api.get_anime_info(anime_id)
  File "C:\Users\desmon0xff\AppData\Local\Programs\Python\Python38\lib\site-packages\animeflv\animeflv.py", line 290, in get_anime_info
    "title": soup.select_one(
AttributeError: 'NoneType' object has no attribute 'string'

C:\Users\desmon0xff\Desktop>python downloader_animeflv.py
Obteniendo enlaces para episodio 1...
Descargando episodio 1 desde MEGA: https://mega.nz/#!s5UHjKzC!GIZnyvJDpc6VZhO4Q04ipHtHPS_8TOd8sCUk4ubS3d4
Episodio 1 guardado como one-punch-man\ep1_MEGA.html
Obteniendo enlaces para episodio 2...
Descargando episodio 2 desde MEGA: https://mega.nz/#!s0FjFKhB!sdZ263UW2cobXTS-azRcNL7gHX3NgRjzUArYRAnQGMA
Episodio 2 guardado como one-punch-man\ep2_MEGA.html
Obteniendo enlaces para episodio 3...
Descargando episodio 3 desde MEGA: https://mega.nz/#!Z4FzlIgb!_y-s6vTAg9JKCWirOwc3plYfbNjum8ryasHiDl5PPPc
Episodio 3 guardado como one-punch-man\ep3_MEGA.html
Obteniendo enlaces para episodio 4...
Descargando episodio 4 desde MEGA: https://mega.nz/#!wkFXgCrA!iWwiBlG_zJTHYxhCC91Z62fEmU6RvsFmC5DWyPWy2hw
Episodio 4 guardado como one-punch-man\ep4_MEGA.html
Obteniendo enlaces para episodio 5...
Descargando episodio 5 desde MEGA: https://mega.nz/#!80FXUALa!AgIwEJh0sby4GNOapMDElMSPToorPcyjWe3l06sZ3Ow
Episodio 5 guardado como one-punch-man\ep5_MEGA.html
Obteniendo enlaces para episodio 6...
Descargando episodio 6 desde MEGA: https://mega.nz/#!R8FD3IgT!bO9U7u-h_flakrV35fy6iCuDiac_pkEL38p5xO9XkUU
Episodio 6 guardado como one-punch-man\ep6_MEGA.html
Obteniendo enlaces para episodio 7...
Descargando episodio 7 desde MEGA: https://mega.nz/#!phETFK5I!ygQuapx6xMhZY2gprN62OTfiAp5A9_DWwvHh9Sp-Y74
Episodio 7 guardado como one-punch-man\ep7_MEGA.html
Obteniendo enlaces para episodio 8...
Descargando episodio 8 desde MEGA: https://mega.nz/#!1lEnGajJ!Dut74R84DYGvv4wC1PdKnuioccXaq6WIBBgi97CZu4M
Episodio 8 guardado como one-punch-man\ep8_MEGA.html
Obteniendo enlaces para episodio 9...
Descargando episodio 9 desde MEGA: https://mega.nz/#!glUjAQDR!i5tMFJol-hF-rjZgue7IlvlZLeTKW4GRJ5cv6KgLO-M
Episodio 9 guardado como one-punch-man\ep9_MEGA.html
Obteniendo enlaces para episodio 10...
Descargando episodio 10 desde MEGA: https://mega.nz/#!t8EXBADb!7SMDQahtbHYAHa2TN0k3QbjuV9ZsGWTPd1iFTRDBIm8
Episodio 10 guardado como one-punch-man\ep10_MEGA.html
Obteniendo enlaces para episodio 11...
Descargando episodio 11 desde MEGA: https://mega.nz/#!AhURFKKZ!LSvVo0SWVP3tl92vZT1QCM-bU3WOqWyydldNj1Z-x1o
Episodio 11 guardado como one-punch-man\ep11_MEGA.html
Obteniendo enlaces para episodio 12...
Descargando episodio 12 desde MEGA: https://mega.nz/#!RtNxEIBC!f7KPFyhjVqZPH6IbBbNil7r_1ZI3gyZbgZd74AtHe9Q
Episodio 12 guardado como one-punch-man\ep12_MEGA.html

C:\Users\desmon0xff\Desktop>python downloader_animeflv.py
```

Este es el codigo de prubas que hice, use el mismo codigo en todas las ejecucciones, las primeras 9 veces fallo, a la decima, decidió funcionar

```python
from animeflv import AnimeFLV
import requests
import os

# Crear instancia de la API
api = AnimeFLV()

# Obtener información del anime
anime_id = "one-punch-man"
anime_info = api.get_anime_info(anime_id)

# Crear carpeta para guardar los episodios
os.makedirs(anime_id, exist_ok=True)

# Iterar sobre los episodios
for ep in sorted(anime_info.episodes, key=lambda e: e.id):
    print(f"Obteniendo enlaces para episodio {ep.id}...")
    links = api.get_links(anime_id, ep.id)

    # Priorizar servidores (elige según preferencia)
    preferred_servers = ['MEGA', '1Fichier', 'Zippyshare', 'Stape']
    selected = next((l for l in links if l.server in preferred_servers), None)

    if not selected:
        print(f"No se encontraron enlaces válidos para el episodio {ep.id}")
        continue

    print(f"Descargando episodio {ep.id} desde {selected.server}: {selected.url}")

    # Descargar archivo (solo si es un enlace directo, como 1Fichier o MEGA, si accesible)
    try:
        # Aquí solo se intenta descargar si el servidor ofrece descarga directa (Zippyshare ya no funciona)
        response = requests.get(selected.url, stream=True)
        filename = os.path.join(anime_id, f"ep{ep.id}_{selected.server}.html")

        # Guardar HTML (enlaces como MEGA requieren tratamiento especial)
        with open(filename, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

        print(f"Episodio {ep.id} guardado como {filename}")
    except Exception as e:
        print(f"Error al descargar el episodio {ep.id}: {e}")

```

**Comment by desmonHak** [comment]
El problema es que en la clase `AnimeFLV` linea 289, no se verifica que la funcion `soup.select_one` devuelva algo valido, en este caso, devuelve None por algun motivo, posiblemente no encuentre los "title" por alguna razon:
```python
information = {
            "title": soup.select_one(
                "body div.Wrapper div.Body div div.Ficha.fchlt div.Container h1.Title"
            ).string,
            "poster": BASE_URL
            + "/"
            + soup.select_one(
                "body div div div div div aside div.AnimeCover div.Image figure img"
            ).get("src", ""),
            "synopsis": soup.select_one(
                "body div div div div div main section div.Description p"
            ).string.strip(),
            "rating": soup.select_one(
                "body div div div.Ficha.fchlt div.Container div.vtshr div.Votes span#votes_prmd"
            ).string,
            "debut": soup.select_one(
                "body div.Wrapper div.Body div div.Container div.BX.Row.BFluid.Sp20 aside.SidebarA.BFixed p.AnmStts"
            ).string,
            "type": soup.select_one(
                "body div.Wrapper div.Body div div.Ficha.fchlt div.Container span.Type"
            ).string,
        }
```

deberia validarse que se encuentre los elementos antes de obtener la cadena de ellos si es que se hay alguna:
```
soup.select_one(
                "body div.Wrapper div.Body div div.Ficha.fchlt div.Container h1.Title"
            )
```

**Comment by dst3v3n** [comment]
Haz validado antes de eso que el ID si sea el correcto?.

Estoy haciendo lo mismo con One piece y no recibia ninguna información por parte del anime. Me di cuenta que no se llama el id "one-piece" sino "one-piece-tv". Eso puede afectar el error que estas teniendo. Deberias validar primero el id con lo siguiente:



```
from animeflv import AnimeFLV


nameAnime = "One-Piece"
nameAnimeId = "one-piece-tv"

with AnimeFLV() as api:
    results = api.search(nameAnime)
    for anime in results:
        print(f"{anime.title} (ID: {anime.id})")

```

Alguien sabe como puedo tener todos los metodos que tiene el paquete y que parametros contiene esos metodos?

**Comment by desmonHak** [comment]
si, lo verifique, y me pasa lo mismo, a veces va y aveces ni va con el mismo id

**Comment by dst3v3n** [comment]
Haz intentado implementar el código de la siguiente forma:

```

from animeflv import AnimeFLV


nameAnime = "One-Piece"
nameAnimeId = "one-piece-tv"

with AnimeFLV() as api:
    results = api.search(nameAnime)
    for anime in results:
        print(f"{anime.title} (ID: {anime.id})")

```

Tu instancias el objeto directamente, intenta usando el with. He estado visualizando el código y hay un procentaje bastante elevado que se requiera usar el with, ya que el código esta creado para usarse con with
